title: M S Mohan Kumar
logo: ![Soft](https://github.com/msmohankumar/msmohankumar.github.io/assets/153971484/2eea5d31-36ae-42b6-aab1-e2dff5404eee)
description: Transforming to Data Scientist 
show_downloads: true 
theme: jekyll-theme-minimal
