title: M S Mohan Kumar
logo: ![WhatsApp Image 2023-12-15 at 09 38 20_f0787aee](https://github.com/msmohankumar/msmohankumar.github.io/assets/153971484/5db9b4ec-296f-400a-b616-bdb0b631116f)
description: Transforming to Data Scientist 
show_downloads: true 
theme: jekyll-theme-minimal
