title: M S Mohan Kumar
logo: ![Profile pic](https://github.com/msmohankumar/msmohankumar.github.io/assets/153971484/86f10e5d-2ec5-4b96-a60f-e9bf998d3aa1)
description: Transforming to Data Scientist 
show_downloads: true 
theme: jekyll-theme-minimal
