title: Shaw Talebi
logo:"C:\Users\msmoh\OneDrive\Desktop\WhatsApp Image 2023-12-15 at 09.38.20_f0787aee.jpg"
description: Transforming to Data Scientist 
show_downloads: true 
theme: jekyll-theme-minimal
