title: M S Mohan Kumar
logo: ![Profile pic](https://github.com/msmohankumar/msmohankumar.github.io/assets/153971484/974b7076-83e9-4e7a-a4a9-4427762dc96f)
description: Transforming to Data Scientist 
show_downloads: true 
theme: jekyll-theme-minimal
